### ISSUE TITLE
Tìm hiểu về các Control Tags: Brush, BrushLabels, Choice, Choices, DateTime, Ellipse, EllipseLabels

### ISSUE THREAD

**Issue by RrrrricardoVuKhang** [ThangNguyen211/Label-Studio-Nhom24#15]

**Comment by RrrrricardoVuKhang** [comment]
- [ ] Tìm hiểu về tag: Brush
- [ ] Tìm hiểu về tag: BrushLabels
- [ ] Tìm hiểu về tag: Choice
- [ ] Tìm hiểu về tag: Choices
- [ ] Tìm hiểu về tag: DateTime
- [ ] Tìm hiểu về tag: Ellipse
- [ ] Tìm hiểu về tag: EllipseLabels
- [ ] Viết báo cáo những gì đã làm

**Comment by 20110725-NguyenHuuThang** [comment]
[20110725-NguyenHuuThang-BaoCaoTuan03](https://docs.google.com/document/d/1C7QjHYEjsGBYcCgPgmDL3VbMNfs0rP2ZLSbCJpOL-iY/edit?usp=sharing)
