### ISSUE TITLE
Tìm hiểu về các Control Tags: HyperTextLabels, KeyPoint, KeyPointLabels, Label, Labels, List, Magicwand

### ISSUE THREAD

**Issue by RrrrricardoVuKhang** [ThangNguyen211/Label-Studio-Nhom24#16]
- [x] Tìm hiểu về tag: HypertTextLabels
- [x] Tìm hiểu về tag: KeyPoint
- [x] Tìm hiểu về tag: KeyPointLabels
- [x] Tìm hiểu về tag: Label
- [x] Tìm hiểu về tag: Labels
- [x] Tìm hiểu về tag: List
- [x] Tìm hiểu về tag: Magicwand
- [x] Viết báo cáo những gì đã làm

**Comment by ThangNguyen211** [comment]
[ControlTag.docx](https://github.com/ThangNguyen211/Label-Studio-Nhom24/files/11128653/ControlTag.docx)
