### ISSUE TITLE
Tìm hiểu về các Control Tags: RectangleLabels, Relation, Relations, Shortcut, Taxonomy, TextArea, TimeSeriesLabels, VideoRectangle

### ISSUE THREAD

**Issue by RrrrricardoVuKhang** [ThangNguyen211/Label-Studio-Nhom24#21]
- [x] Tìm hiểu về Tags: RectangleLabels
- [x] Tìm hiểu về Tags: Relation
- [x] Tìm hiểu về Tags: Relations
- [x] Tìm hiểu về Tags: Shortcut
- [x] Tìm hiểu về Tags: Taxonomy
- [x] Tìm hiểu về Tags: TextArea
- [x] Tìm hiểu về Tags: TimeSeriesLabels
- [x] Tìm hiểu về Tags: VideoRectagle
- [x] Viết báo cáo những gì đã làm

**Comment by 20110725-NguyenHuuThang** [comment]
[Tìm hiểu về các Control Tags_Tuần 4](https://docs.google.com/document/d/1gZCy5RtO1ct7Bt9R30Oz_YOOoQNcPJ8y8iX9UP2joj8/edit?usp=sharing)
