### ISSUE TITLE
Tìm hiểu về các Visual & Experience Tags: Collapse, Filter, Header, Style, View

### ISSUE THREAD

**Issue by RrrrricardoVuKhang** [ThangNguyen211/Label-Studio-Nhom24#22]
- [x] Tìm hiểu về Tags: Collapse
- [x] Tìm hiểu về Tags: Filter
- [x] Tìm hiểu về Tags: Header
- [x] Tìm hiểu về Tags: Style
- [x] Tìm hiểu về Tags: View
- [x] Viết báo cáo những gì đã làm

**Comment by ThangNguyen211** [comment]
[](url)https://docs.google.com/document/d/1jBDQwHRJ9GofXe7JbBEEb6-NsQeAJGPJAkZvj6emlEU/edit#
