### ISSUE TITLE
Làm tổng hợp và tạo powerpoint mô tả

### ISSUE THREAD

**Issue by ThangNguyen211** [ThangNguyen211/Label-Studio-Nhom24#23]
- [x] Tổng hợp báo cáo word về Virtualization và Containerization
- [x] Thiết kế powerpoint
- [x] Bổ sung hình ảnh minh họa
- [x] Viết báo cáo những gì đã làm

**Comment by 20110725-NguyenHuuThang** [comment]
[week12.pptx](https://github.com/ThangNguyen211/Label-Studio-Nhom24/files/11321331/week12.pptx)
