### ISSUE TITLE
Tìm hiểu về các tool liên quan đến virtualization và containerization

### ISSUE THREAD

**Issue by ThangNguyen211** [ThangNguyen211/Label-Studio-Nhom24#24]
- [x] Định nghĩa và các chức năng của VMWare Workstation
- [x] Cách hoạt động của VMWare  Workstation
- [x] Định nghĩa và nền tảng của Docker
- [x] Các thành phần chính của Docker
- [x] Mục đích sử dụng của Docker
- [x] Kiến trúc của Docker
- [x] Viết báo cáo những gì đã làm

**Comment by RrrrricardoVuKhang** [comment]
[VMWare và Docker](https://docs.google.com/document/d/1UoofGcIdFTf-Z4Ya8Wg9l0aIne3tQ-HHUb03nQIIUXk/edit?usp=sharing)
