### ISSUE TITLE
Viết đặc tả usecase

### ISSUE THREAD

**Issue by RrrrricardoVuKhang** [ThangNguyen211/Label-Studio-Nhom24#4]
- [x] 100% các chức năng được về usecase diagram 

- [x] 100% code được về class diagram

- [x] 100% code được về activity diagram

**Comment by 20110725-NguyenHuuThang** [comment]
[Usercase Diagram, Class Diagram, Activity Diagram](https://docs.google.com/document/d/15Vde9m7-NMQH2KnhY0mvWAuMGba1NaTySAlaDssDQug/edit)
