### ISSUE TITLE
Viết Flow Events cho các chức năng trong hệ thống

### ISSUE THREAD

**Issue by ThangNguyen211** [ThangNguyen211/Label-Studio-Nhom24#9]
- [x] Viết flow events cho đăng ký 

- [x] Viết flow events cho đăng nhập

- [x] Viết flow events cho tạo project/chọn template,...  

- [x] Viết flow events cho import dữ liệu

- [x] Viết flow events cho label dữ liệu

- [x] Viết flow events cho export dữ liệu

- [x] Viết báo cáo những gì đã làm

**Comment by 20110725-NguyenHuuThang** [comment]
[20110725_NguyenHuuThang_NhungViecDaLamTrongTuan02](https://docs.google.com/document/d/14RT2-4-wrHPycLzqMhYQf0IAoeolgB9zXA_Qm4kg8nI/edit?usp=sharing)
